name: Pipeline

defaults:
  run:
    shell: bash

on:
  push:
    branches-ignore:
      - master

jobs:
  install-test:
    runs-on: ubuntu-latest
    container: biomapas/cicd-full:5.0.0

    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: |
          npm install -g aws-cdk
          pip install . --upgrade
          pip list

      - name: Test
        run: |
          pip install -r b_cfn_lambda_integration_test/requirements.txt
          pytest b_cfn_lambda_integration_test/unit
